# Generated by Django 4.1 on 2022-08-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe el nombre del director', max_length=64)),
                ('apellido', models.CharField(help_text='Escribe el apellido del director', max_length=64)),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Pon el título de la película', max_length=64)),
                ('año_de_estreno', models.IntegerField()),
                ('sinopsis', models.TextField(help_text='Escribe la sinopsis de la película', max_length=100)),
                ('dirigido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.directores')),
            ],
        ),
        migrations.AddField(
            model_name='directores',
            name='peliculas_dirigidas',
            field=models.ManyToManyField(to='directores.peliculas'),
        ),
    ]
