# Generated by Django 4.1 on 2022-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0003_peliculas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='url',
            field=models.URLField(default='https://kangsblackbeltacademy.com/wp-content/uploads/2017/04/default-image.jpg'),
        ),
    ]
