# Generated by Django 4.1 on 2022-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0004_alter_peliculas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='peliculas_dirigidas',
            field=models.ManyToManyField(blank=True, null=True, to='directores.peliculas'),
        ),
    ]
