# Generated by Django 4.1 on 2022-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0005_alter_directores_peliculas_dirigidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='sinopsis',
            field=models.TextField(help_text='Escribe la sinopsis de la película', max_length=800),
        ),
    ]
