# Generated by Django 4.1 on 2022-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0006_alter_peliculas_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='sinopsis',
            field=models.TextField(help_text='Escribe la sinopsis de la película', max_length=1000),
        ),
    ]
