# Generated by Django 4.1 on 2022-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0007_alter_peliculas_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='url',
            new_name='urlImagen',
        ),
        migrations.AddField(
            model_name='directores',
            name='urlImagen',
            field=models.URLField(default='https://kangsblackbeltacademy.com/wp-content/uploads/2017/04/default-image.jpg'),
        ),
    ]
