# Generated by Django 4.1 on 2022-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0008_rename_url_peliculas_urlimagen_directores_urlimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='nacionalidad',
            field=models.CharField(help_text='Pon la nacionalidad del director', max_length=64, null=True),
        ),
    ]
